# docker build -t registry.nano35.ru/nano35-service/web-cmd:0.1.2 -f WebCmd.App/Dockerfile .
# docker push registry.nano35.ru/nano35-service/web-cmd:0.1.2

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: service-preview
  name: web-cmd
  labels:
    app: nano35
    scope: service
    role: domain
    state: preview
    domain: web-cmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-cmd
  template:
    metadata:
      name: web-cmd
      labels:
        app: web-cmd
    spec:
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: NotIn
                    values:
                      - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - web-cmd
              topologyKey: "kubernetes.io/hostname"
      containers:
        - image: registry.nano35.ru/nano35-service/web-cmd:0.1.2
          imagePullPolicy: Always
          name: service-web-cmd
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Publish
            - name: ASPNETCORE_URLS
              value: http://+:81
            - name: DOMAIN_NAME
              value: Service-web-cmd
            - name: HOSTS
              value: "{\"Hosts\": [{\"type\": 0,\"host\": \"10.10.10.31\", \"args\": \"\"},{\"type\": 0,\"host\": \"10.10.10.70\",\"args\": \"\"},{\"type\": 1,\"host\": \"10.10.10.70\",\"args\": \"\"},{\"type\": 2,\"host\": \"http://10.10.10.31:9100/metrics\",\"args\": \"\"},{\"type\": 3,\"host\": \"localhost\",\"args\": \"12345\"},{\"type\": 4,\"host\": \"10.10.10.31\",\"args\": \"{ 'command': 'ip a', 'username': 'root', 'password': 'N0t_@_Sp@1nder' }\"}]}"

          ports:
            - containerPort: 81
              name: rest